// GENERATED by scripts/registry.mjs — do not edit by hand.
// Re-run it whenever a file is added to assets/plans or assets/photos.
//
// Why this exists: the admin stores homes as JSON, and JSON cannot hold a
// static import. A key here resolves to one, so a home written by the admin
// keeps the intrinsic size and the build-time blur placeholder that a bare
// string src would throw away.
import type { StaticImageData } from "next/image";

import plan_v01_ground from "@/assets/plans/v01-ground.webp";
import plan_v01_lower from "@/assets/plans/v01-lower.webp";
import plan_v02_ground from "@/assets/plans/v02-ground.webp";
import plan_v02_lower from "@/assets/plans/v02-lower.webp";
import plan_v03_ground from "@/assets/plans/v03-ground.webp";
import plan_v03_lower from "@/assets/plans/v03-lower.webp";
import plan_v04_ground from "@/assets/plans/v04-ground.webp";
import plan_v04_lower from "@/assets/plans/v04-lower.webp";
import plan_v05_ground from "@/assets/plans/v05-ground.webp";
import plan_v05_lower from "@/assets/plans/v05-lower.webp";
import plan_v06_ground from "@/assets/plans/v06-ground.webp";
import plan_v06_lower from "@/assets/plans/v06-lower.webp";
import plan_v07_ground from "@/assets/plans/v07-ground.webp";
import plan_v07_lower from "@/assets/plans/v07-lower.webp";
import plan_v08_ground from "@/assets/plans/v08-ground.webp";
import plan_v08_lower from "@/assets/plans/v08-lower.webp";
import plan_v09_ground from "@/assets/plans/v09-ground.webp";
import plan_v09_lower from "@/assets/plans/v09-lower.webp";
import plan_v10_ground from "@/assets/plans/v10-ground.webp";
import plan_v10_lower from "@/assets/plans/v10-lower.webp";
import plan_v11_ground from "@/assets/plans/v11-ground.webp";
import plan_v11_lower from "@/assets/plans/v11-lower.webp";
import plan_v12_ground from "@/assets/plans/v12-ground.webp";
import plan_v12_lower from "@/assets/plans/v12-lower.webp";
import plan_v13_ground from "@/assets/plans/v13-ground.webp";
import plan_v13_lower from "@/assets/plans/v13-lower.webp";
import plan_v14_extra from "@/assets/plans/v14-extra.webp";
import plan_v14_ground from "@/assets/plans/v14-ground.webp";
import plan_v14_lower from "@/assets/plans/v14-lower.webp";
import plan_v15_ground from "@/assets/plans/v15-ground.webp";
import plan_v15_lower from "@/assets/plans/v15-lower.webp";
import plan_v16_ground from "@/assets/plans/v16-ground.webp";
import plan_v16_lower from "@/assets/plans/v16-lower.webp";
import plan_v17_ground from "@/assets/plans/v17-ground.webp";
import plan_v17_lower from "@/assets/plans/v17-lower.webp";
import photo_amenities_night from "@/assets/photos/amenities-night.jpg";
import photo_balcony from "@/assets/photos/balcony.jpg";
import photo_contact_court from "@/assets/photos/contact-court.jpg";
import photo_contact_map from "@/assets/photos/contact-map.jpg";
import photo_courtyard from "@/assets/photos/courtyard.jpg";
import photo_dilijan_aerial from "@/assets/photos/dilijan-aerial.jpg";
import photo_dilijan_forest from "@/assets/photos/dilijan-forest.jpg";
import photo_facade from "@/assets/photos/facade.jpg";
import photo_half_stone_bath from "@/assets/photos/half-stone-bath.jpg";
import photo_half_stone_bedroom from "@/assets/photos/half-stone-bedroom.jpg";
import photo_half_stone_kitchen from "@/assets/photos/half-stone-kitchen.jpg";
import photo_hero_day from "@/assets/photos/hero-day.jpg";
import photo_hero_night from "@/assets/photos/hero-night.jpg";
import photo_hero_sky from "@/assets/photos/hero-sky.jpg";
import photo_homes_tail_colonnade from "@/assets/photos/homes-tail-colonnade.jpg";
import photo_homes_tile_ararat from "@/assets/photos/homes-tile-ararat.jpg";
import photo_homes_tile_living from "@/assets/photos/homes-tile-living.jpg";
import photo_homes_tile_pergola from "@/assets/photos/homes-tile-pergola.jpg";
import photo_inter_bedroom from "@/assets/photos/inter-bedroom.jpg";
import photo_inter_dining from "@/assets/photos/inter-dining.jpg";
import photo_inter_kitchen from "@/assets/photos/inter-kitchen.jpg";
import photo_interior_bath from "@/assets/photos/interior-bath.jpg";
import photo_interior_bedroom from "@/assets/photos/interior-bedroom.jpg";
import photo_interior_kitchen from "@/assets/photos/interior-kitchen.jpg";
import photo_interior_living from "@/assets/photos/interior-living.jpg";
import photo_komitas_p7_bath from "@/assets/photos/komitas-p7-bath.jpg";
import photo_komitas_p7_kitchen from "@/assets/photos/komitas-p7-kitchen.jpg";
import photo_komitas_p7_landing from "@/assets/photos/komitas-p7-landing.jpg";
import photo_orran_a4_bath from "@/assets/photos/orran-a4-bath.jpg";
import photo_orran_a4_bedroom from "@/assets/photos/orran-a4-bedroom.jpg";
import photo_orran_a9_hall from "@/assets/photos/orran-a9-hall.jpg";
import photo_orran_a9_kitchen from "@/assets/photos/orran-a9-kitchen.jpg";
import photo_orran_a9_stair from "@/assets/photos/orran-a9-stair.jpg";
import photo_orran_b2_bath from "@/assets/photos/orran-b2-bath.jpg";
import photo_orran_b2_bedroom from "@/assets/photos/orran-b2-bedroom.jpg";
import photo_orran_b2_kitchen from "@/assets/photos/orran-b2-kitchen.jpg";
import photo_pine_3_bathroom from "@/assets/photos/pine-3-bathroom.jpg";
import photo_pine_3_bedroom from "@/assets/photos/pine-3-bedroom.jpg";
import photo_pine_3_kitchen from "@/assets/photos/pine-3-kitchen.jpg";
import photo_pine_7_kitchen from "@/assets/photos/pine-7-kitchen.jpg";
import photo_pine_7_living from "@/assets/photos/pine-7-living.jpg";
import photo_place_complex from "@/assets/photos/place-complex.jpg";
import photo_place_garden from "@/assets/photos/place-garden.jpg";
import photo_place_terrace from "@/assets/photos/place-terrace.jpg";
import photo_pool from "@/assets/photos/pool.jpg";
import photo_pull_villa from "@/assets/photos/pull-villa.jpg";
import photo_saryan_c12_bath from "@/assets/photos/saryan-c12-bath.jpg";
import photo_saryan_c12_bedroom from "@/assets/photos/saryan-c12-bedroom.jpg";
import photo_saryan_c12_kitchen from "@/assets/photos/saryan-c12-kitchen.jpg";
import photo_sevan_lake from "@/assets/photos/sevan-lake.jpg";
import photo_shore_t2_bathroom from "@/assets/photos/shore-t2-bathroom.jpg";
import photo_shore_t2_bedroom from "@/assets/photos/shore-t2-bedroom.jpg";
import photo_shore_t2_kitchen from "@/assets/photos/shore-t2-kitchen.jpg";
import photo_stair from "@/assets/photos/stair.jpg";
import photo_terrace from "@/assets/photos/terrace.jpg";
import photo_tsaghkadzor_slope from "@/assets/photos/tsaghkadzor-slope.jpg";
import photo_type_balcony from "@/assets/photos/type-balcony.jpg";
import photo_type_courtyard from "@/assets/photos/type-courtyard.jpg";
import photo_type_garden from "@/assets/photos/type-garden.jpg";
import photo_valley from "@/assets/photos/valley.jpg";
import photo_views_terrace from "@/assets/photos/views-terrace.jpg";
import photo_yerevan_day from "@/assets/photos/yerevan-day.jpg";
import photo_yerevan_night from "@/assets/photos/yerevan-night.jpg";

export const plans: Record<string, StaticImageData> = {
  "v01-ground": plan_v01_ground,
  "v01-lower": plan_v01_lower,
  "v02-ground": plan_v02_ground,
  "v02-lower": plan_v02_lower,
  "v03-ground": plan_v03_ground,
  "v03-lower": plan_v03_lower,
  "v04-ground": plan_v04_ground,
  "v04-lower": plan_v04_lower,
  "v05-ground": plan_v05_ground,
  "v05-lower": plan_v05_lower,
  "v06-ground": plan_v06_ground,
  "v06-lower": plan_v06_lower,
  "v07-ground": plan_v07_ground,
  "v07-lower": plan_v07_lower,
  "v08-ground": plan_v08_ground,
  "v08-lower": plan_v08_lower,
  "v09-ground": plan_v09_ground,
  "v09-lower": plan_v09_lower,
  "v10-ground": plan_v10_ground,
  "v10-lower": plan_v10_lower,
  "v11-ground": plan_v11_ground,
  "v11-lower": plan_v11_lower,
  "v12-ground": plan_v12_ground,
  "v12-lower": plan_v12_lower,
  "v13-ground": plan_v13_ground,
  "v13-lower": plan_v13_lower,
  "v14-extra": plan_v14_extra,
  "v14-ground": plan_v14_ground,
  "v14-lower": plan_v14_lower,
  "v15-ground": plan_v15_ground,
  "v15-lower": plan_v15_lower,
  "v16-ground": plan_v16_ground,
  "v16-lower": plan_v16_lower,
  "v17-ground": plan_v17_ground,
  "v17-lower": plan_v17_lower,
};

export const photos: Record<string, StaticImageData> = {
  "amenities-night": photo_amenities_night,
  "balcony": photo_balcony,
  "contact-court": photo_contact_court,
  "contact-map": photo_contact_map,
  "courtyard": photo_courtyard,
  "dilijan-aerial": photo_dilijan_aerial,
  "dilijan-forest": photo_dilijan_forest,
  "facade": photo_facade,
  "half-stone-bath": photo_half_stone_bath,
  "half-stone-bedroom": photo_half_stone_bedroom,
  "half-stone-kitchen": photo_half_stone_kitchen,
  "hero-day": photo_hero_day,
  "hero-night": photo_hero_night,
  "hero-sky": photo_hero_sky,
  "homes-tail-colonnade": photo_homes_tail_colonnade,
  "homes-tile-ararat": photo_homes_tile_ararat,
  "homes-tile-living": photo_homes_tile_living,
  "homes-tile-pergola": photo_homes_tile_pergola,
  "inter-bedroom": photo_inter_bedroom,
  "inter-dining": photo_inter_dining,
  "inter-kitchen": photo_inter_kitchen,
  "interior-bath": photo_interior_bath,
  "interior-bedroom": photo_interior_bedroom,
  "interior-kitchen": photo_interior_kitchen,
  "interior-living": photo_interior_living,
  "komitas-p7-bath": photo_komitas_p7_bath,
  "komitas-p7-kitchen": photo_komitas_p7_kitchen,
  "komitas-p7-landing": photo_komitas_p7_landing,
  "orran-a4-bath": photo_orran_a4_bath,
  "orran-a4-bedroom": photo_orran_a4_bedroom,
  "orran-a9-hall": photo_orran_a9_hall,
  "orran-a9-kitchen": photo_orran_a9_kitchen,
  "orran-a9-stair": photo_orran_a9_stair,
  "orran-b2-bath": photo_orran_b2_bath,
  "orran-b2-bedroom": photo_orran_b2_bedroom,
  "orran-b2-kitchen": photo_orran_b2_kitchen,
  "pine-3-bathroom": photo_pine_3_bathroom,
  "pine-3-bedroom": photo_pine_3_bedroom,
  "pine-3-kitchen": photo_pine_3_kitchen,
  "pine-7-kitchen": photo_pine_7_kitchen,
  "pine-7-living": photo_pine_7_living,
  "place-complex": photo_place_complex,
  "place-garden": photo_place_garden,
  "place-terrace": photo_place_terrace,
  "pool": photo_pool,
  "pull-villa": photo_pull_villa,
  "saryan-c12-bath": photo_saryan_c12_bath,
  "saryan-c12-bedroom": photo_saryan_c12_bedroom,
  "saryan-c12-kitchen": photo_saryan_c12_kitchen,
  "sevan-lake": photo_sevan_lake,
  "shore-t2-bathroom": photo_shore_t2_bathroom,
  "shore-t2-bedroom": photo_shore_t2_bedroom,
  "shore-t2-kitchen": photo_shore_t2_kitchen,
  "stair": photo_stair,
  "terrace": photo_terrace,
  "tsaghkadzor-slope": photo_tsaghkadzor_slope,
  "type-balcony": photo_type_balcony,
  "type-courtyard": photo_type_courtyard,
  "type-garden": photo_type_garden,
  "valley": photo_valley,
  "views-terrace": photo_views_terrace,
  "yerevan-day": photo_yerevan_day,
  "yerevan-night": photo_yerevan_night,
};

/** Resolve a plan key, or throw with the key that failed — a missing drawing
 *  must stop the build, never render as a gap on a home's page. */
export const plan = (key: string): StaticImageData => {
  const v = plans[key];
  if (!v) throw new Error(`imageRegistry: no plan "${key}" (run node scripts/registry.mjs)`);
  return v;
};

/** Resolve a photo key. Returns undefined rather than throwing: a home with
 *  no photography is a supported state, and falls back to its place's set. */
export const photo = (key: string): StaticImageData | undefined => photos[key];

export const planKeys = Object.keys(plans);
export const photoKeys = Object.keys(photos);
