// THE IMAGE REGISTRY, generated.
//
//   node scripts/registry.mjs   → lib/imageRegistry.ts
//
// The admin stores a home as JSON, and JSON cannot hold a static import. But
// a string path handed to next/image loses everything static imports buy on
// this site: the real intrinsic width and height, and the blur placeholder
// generated at build time from the file itself.
//
// So JSON names an image by KEY and this file resolves the key to the static
// import. Both halves are kept honest by regenerating rather than editing:
// the registry is exactly what is on disk, and a key that no longer resolves
// is a build error rather than a broken picture in production.
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, "$1")), "..");
const OUT = path.join(ROOT, "lib", "imageRegistry.ts");

const folders = [
  { dir: "assets/plans", prefix: "plan", exts: /\.(webp|jpg|png)$/i },
  { dir: "assets/photos", prefix: "photo", exts: /\.(jpe?g|png|webp)$/i },
];

const ident = (prefix, file) =>
  prefix + "_" + file.replace(/\.[^.]+$/, "").replace(/[^a-zA-Z0-9]+/g, "_");

const imports = [];
const rows = { plan: [], photo: [] };

for (const f of folders) {
  const abs = path.join(ROOT, f.dir);
  if (!fs.existsSync(abs)) continue;
  for (const file of fs.readdirSync(abs).filter((n) => f.exts.test(n)).sort()) {
    const id = ident(f.prefix, file);
    imports.push(`import ${id} from "@/${f.dir}/${file}";`);
    rows[f.prefix].push(`  "${file.replace(/\.[^.]+$/, "")}": ${id},`);
  }
}

const out = `// GENERATED by scripts/registry.mjs — do not edit by hand.
// Re-run it whenever a file is added to assets/plans or assets/photos.
//
// Why this exists: the admin stores homes as JSON, and JSON cannot hold a
// static import. A key here resolves to one, so a home written by the admin
// keeps the intrinsic size and the build-time blur placeholder that a bare
// string src would throw away.
import type { StaticImageData } from "next/image";

${imports.join("\n")}

export const plans: Record<string, StaticImageData> = {
${rows.plan.join("\n")}
};

export const photos: Record<string, StaticImageData> = {
${rows.photo.join("\n")}
};

/** Resolve a plan key, or throw with the key that failed — a missing drawing
 *  must stop the build, never render as a gap on a home's page. */
export const plan = (key: string): StaticImageData => {
  const v = plans[key];
  if (!v) throw new Error(\`imageRegistry: no plan "\${key}" (run node scripts/registry.mjs)\`);
  return v;
};

/** Resolve a photo key. Returns undefined rather than throwing: a home with
 *  no photography is a supported state, and falls back to its place's set. */
export const photo = (key: string): StaticImageData | undefined => photos[key];

export const planKeys = Object.keys(plans);
export const photoKeys = Object.keys(photos);
`;

fs.writeFileSync(OUT, out);
console.log(
  `lib/imageRegistry.ts — ${rows.plan.length} plans, ${rows.photo.length} photographs`,
);
